  CREATE TABLE "SYSTEM"."USUARIO" 
   (	"LOGIN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CLIENTE" FLOAT(126) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"FECHAALTA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FECHABAJA" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'A' NOT NULL ENABLE, 
	"INTENTOS" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
	"FECHAREVOCADO" DATE, 
	"FECHA_VIGENCIA" DATE, 
	"NO_ACCESO" NUMBER(*,0) DEFAULT 0, 
	"APELLIDO_PATERNO" VARCHAR2(50 BYTE), 
	"APELLIDO_MATERNO" VARCHAR2(50 BYTE), 
	"AREA" NUMBER(4,0), 
	"FECHAMODIFICACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;